export const clerkAppearance = {
  variables: {
    colorPrimary: '#080808',
    colorBackground: '#FFFFFF',
    colorText: '#080808',
    colorTextSecondary: '#706F70',
    colorInputBackground: '#FFFFFF',
    colorInputText: '#080808',
    colorNeutral: '#EBEDF1',
    colorDanger: '#080808',
    borderRadius: '12px',
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
  },
  layout: {
    socialButtonsPlacement: 'top',
    socialButtonsVariant: 'blockButton',
    shimmer: false,
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full shadow-none',
    card: 'bg-white border border-[#D4D8DF] rounded-2xl shadow-none w-full p-6 sm:p-8',
    header: 'hidden',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    socialButtons: 'gap-2',
    socialButtonsBlockButton:
      'border border-[#D4D8DF] bg-white text-[#080808] rounded-xl h-11 hover:bg-[#F5F6F8] transition-colors',
    socialButtonsBlockButtonText: 'text-[#080808] text-sm font-medium',
    socialButtonsProviderIcon: 'opacity-90',
    dividerLine: 'bg-[#EBEDF1]',
    dividerText: 'text-[#ACADB1] text-xs',
    formFieldLabel: 'text-[#706F70] text-sm font-medium mb-1.5',
    formFieldInput:
      'bg-white border border-[#D4D8DF] text-[#080808] rounded-xl h-11 px-3.5 text-sm placeholder:text-[#ACADB1] focus:border-[#ACADB1] focus:ring-0 transition-colors',
    formFieldInputShowPasswordButton: 'text-[#ACADB1] hover:text-[#706F70]',
    formButtonPrimary:
      'bg-[#080808] text-white rounded-full h-11 text-sm font-medium hover:opacity-80 transition-opacity normal-case',
    formButtonReset: 'text-[#706F70] hover:text-[#080808] transition-colors',
    footerAction: 'justify-center',
    footerActionText: 'text-[#706F70] text-sm',
    footerActionLink: 'text-[#080808] text-sm font-medium hover:opacity-70 transition-opacity',
    identityPreview: 'border border-[#EBEDF1] rounded-xl bg-[#F5F6F8]',
    identityPreviewText: 'text-[#080808] text-sm',
    identityPreviewEditButton: 'text-[#706F70] text-sm',
    formFieldSuccessText: 'text-[#706F70] text-xs',
    formFieldErrorText: 'text-[#353536] text-xs',
    formFieldWarningText: 'text-[#706F70] text-xs',
    formFieldHintText: 'text-[#ACADB1] text-xs',
    otpCodeFieldInput: 'border border-[#D4D8DF] rounded-xl text-[#080808]',
    phoneInputBox: 'bg-white border border-[#D4D8DF] rounded-xl h-11',
    phoneInputInput: 'text-[#080808] text-sm',
    selectButton:
      'bg-white border border-[#D4D8DF] rounded-xl text-[#080808] hover:bg-[#F5F6F8]',
    selectOptionsContainer: 'bg-white border border-[#D4D8DF] rounded-xl',
    selectOption: 'text-[#080808] hover:bg-[#F5F6F8]',
    alert: 'border border-[#D4D8DF] bg-[#F5F6F8] rounded-xl text-[#706F70]',
    alertText: 'text-[#706F70] text-sm',
    backLink: 'text-[#706F70] hover:text-[#080808] text-sm transition-colors',
    navbar: 'hidden',
    logoBox: 'hidden',
    footer: 'bg-transparent pt-2',
    form: 'gap-4',
    main: 'gap-6',
  },
}
